---

- hosts: EC2_server
  become: true
  tasks:

    - name: Copy Kubernetes Manifests from GitHub
      copy:
        src: ../Kubernetes/
        dest: /home/ubuntu/kubernetes/
        mode: "777"

    - name: Copy setup.sh from GitHub
      copy:
        src: ../setup.sh
        dest: /home/ubuntu/
        mode: "777"

    - name: Run setup.sh
      shell: "./setup.sh"

    - name: Delete Minikube
      shell: "minikube delete"

    - name: Start Minikube
      become: false
      shell: "minikube start --driver=none --container-runtime=docker --cri-socket=/var/run/cri-dockerd.sock"

    - name: Apply Kubernetes Manifests
      become: false
      shell: "kubectl apply -f /home/ubuntu/kubernetes/"

    - name: Port Forwarding
      become: false
      shell: "sleep 10 && kubectl port-forward service/my-spotify-service 8080:8000 -n elk"

    

