name: dockerimage
run-name: Docker Pushing

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          - name: MySpotify
            context: ./MySpotify/
            tag: 26marco10/my-spotify:latest
          

    #---------------------------------#
    #   Build and Push Docker Image   #
    #   on the DockerHub Registry     #
    #---------------------------------#

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into Docker Hub registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Replace localhost with AWS domain
        run: |
          sed -i 's|localhost|ec2-54-160-125-12.compute-1.amazonaws.com|g' $(grep -rl 'localhost' .)

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          tags: ${{ matrix.image.tag }}
          context: ${{ matrix.image.context }}
          push: true