name: dockerimage
run-name: Docker Pushing

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          - name: MySpotify
            context: ./MySpotify/
            tag: 26marco10/my-spotify:latest
          

    #---------------------------------#
    #   Build and Push Docker Image   #
    #   on the DockerHub Registry     #
    #---------------------------------#

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into Docker Hub registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Replace localhost with AWS domain in html files
        uses: richardrigutins/replace-in-files@v2
        with:
          files: '**/*.html'
          search-text: 'localhost'
          replacement-text: 'ec2-54-160-125-12.compute-1.amazonaws.com'
          encoding: 'utf8'
          max-parallelism: 10

      - name: Replace localhost with AWS domain in py files
        uses: richardrigutins/replace-in-files@v2
        with:
          files: '**/*.py'
          search-text: 'localhost'
          replacement-text: 'ec2-54-160-125-12.compute-1.amazonaws.com'
          encoding: 'utf8'
          max-parallelism: 10

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          tags: ${{ matrix.image.tag }}
          context: ${{ matrix.image.context }}
          push: true
  
  connect-to-ec2:
    needs: build-and-push

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configura chiave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/aws_key.pem
          chmod 600 ~/.ssh/aws_key.pem

      - name: Aggiungi host remoto a known_hosts
        run: |
          ssh-keyscan -H dominio >> ~/.ssh/known_hosts

      - name: Copia file su istanza AWS
        run: scp -i ~/.ssh/aws_key.pem setup.sh ubuntu@ec2-54-160-125-12.compute-1.amazonaws.com:/home/ubuntu/

    